# Generated by Django 5.2.7 on 2025-11-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_solicitud', models.CharField(max_length=10, unique=True)),
                ('sucursal', models.CharField(choices=[('Santiago', 'Santiago'), ('Coquimbo', 'Coquimbo'), ('Osorno', 'Osorno')], max_length=20)),
                ('nombre_cliente', models.CharField(max_length=120)),
                ('rut_cliente', models.CharField(max_length=20)),
                ('tipo_carga', models.CharField(choices=[('General', 'General'), ('Refrigerada', 'Refrigerada'), ('Peligrosa', 'Peligrosa'), ('Maquinaria Pesada', 'Maquinaria Pesada'), ('Granel', 'Granel')], max_length=30)),
                ('peso_kg', models.FloatField(help_text='Peso en kilogramos (usa toneladas×1000 si aplica)')),
                ('volumen_m3', models.FloatField(help_text='Volumen en metros cúbicos')),
                ('fecha_retiro', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('direccion_retiro', models.CharField(max_length=200)),
                ('direccion_entrega', models.CharField(max_length=200)),
                ('indicaciones_especiales', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Finalizada', 'Finalizada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('recursos_necesarios', models.CharField(blank=True, max_length=200)),
                ('tiempo_viaje_estimado', models.CharField(blank=True, max_length=120)),
                ('costo_combustible_clp', models.IntegerField(blank=True, null=True)),
                ('costo_personal_clp', models.IntegerField(blank=True, null=True)),
                ('costo_peajes_clp', models.IntegerField(blank=True, null=True)),
                ('permisos_especiales_clp', models.IntegerField(blank=True, null=True)),
                ('riesgo_logistico', models.CharField(blank=True, max_length=40)),
                ('accion_pendiente', models.CharField(blank=True, max_length=120)),
                ('estado_final', models.CharField(blank=True, max_length=20)),
                ('motivo_cierre', models.CharField(blank=True, max_length=200)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
