# Generated by Django 5.2.7 on 2025-11-12 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='peso_kg',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='volumen_m3',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='peso_unidad',
            field=models.CharField(choices=[('kg', 'Kilogramos (kg)'), ('ton', 'Toneladas (ton)')], default='kg', max_length=3),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='peso_valor',
            field=models.FloatField(default=0, help_text='Valor del peso según unidad seleccionada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='volumen_m2',
            field=models.FloatField(default=0, help_text='Volumen en metros cuadrados (m²)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='sucursal',
            field=models.CharField(choices=[('Santiago', 'Santiago'), ('Coquimbo', 'Coquimbo'), ('Osorno', 'Osorno')], default='Santiago', max_length=20),
        ),
    ]
