# Generated by Django 5.2.7 on 2025-11-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_remove_solicitud_peso_kg_remove_solicitud_volumen_m3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id_solicitud',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
    ]
