# Generated by Django 5.2.7 on 2025-11-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_solicitud_id_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='correo',
            field=models.CharField(default='sin-correo@acme.cl', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(default='+56900000000', max_length=20),
            preserve_default=False,
        ),
    ]
