# Generated by Django 5.2.7 on 2025-11-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_solicitud_correo_solicitud_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Finalizada', 'Finalizada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=40),
        ),
    ]
